.\"
.\" Copyright (c) 2011-2018, Stefan Vogt, Brian Cassidy, and Frederic Cambus
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\"   * Redistributions of source code must retain the above copyright
.\"     notice, this list of conditions and the following disclaimer.
.\"
.\"   * Redistributions in binary form must reproduce the above copyright
.\"     notice, this list of conditions and the following disclaimer in the
.\"     documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd $Mdocdate: June 19 2018 $
.Dt ANSILOVE 1
.Os
.Sh NAME
.Nm ansilove
.Nd ANSI / ASCII art to PNG converter
.Sh SYNOPSIS
.Nm
.Op Fl ehirsv
.Op Fl b Ar bits
.Op Fl c Ar columns
.Op Fl f Ar font
.Op Fl m Ar mode
.Op Fl o Ar file
.Op Fl R Ar factor
.Ar file
.Sh DESCRIPTION
.Nm
is an ANSI / ASCII art to PNG converter, allowing to convert ANSI and
artscene-related file formats into PNG images, supporting ANSI (.ANS),
PCBoard (.PCB), Binary (.BIN), Artworx (.ADF), iCE Draw (.IDF),
Tundra (.TND) and XBin (.XB) formats.
.Pp
It creates size optimized 4-bit PNG files and supports SAUCE (Standard
Architecture for Universal Comment Extentions), 80x25 and 80x50 PC fonts
(including all the 14 MS-DOS charsets), Amiga fonts, and iCE colors.
.Pp
The options are as follows:
.Bl -tag -width 10n
.It Fl b Ar bits
Set to 9 to render 9th column of block characters (default: 8)
.It Fl c Ar columns
Adjust number of columns for BIN files (default: 160)
.It Fl e
Print a list of examples
.It Fl f Ar font
Select font for supported formats.
.Pp
Valid options for PC fonts are:
.Bl -tag -width Er
.It Ic 80x25
Default (Code page 437)
.It Ic 80x50
80x50 mode (Code page 437)
.It Ic baltic
Baltic (Code page 775)
.It Ic cyrillic
Cyrillic (Code page 855)
.It Ic french-canadian
French Canadian (code page 863)
.It Ic greek
Greek (code page 737)
.It Ic greek-869
Greek-869 (code page 869)
.It Ic hebrew
Hebrew (code page 862)
.It Ic icelandic
Icelandic (Code page 861)
.It Ic latin1
Latin1 (code page 850)
.It Ic latin2
Latin2 (code page 852)
.It Ic nordic
Nordic (code page 865)
.It Ic portuguese
Portuguese (Code page 860)
.It Ic russian
Russian (code page 866)
.It Ic turkish
Turkish (code page 857)
.It Ic terminus
Terminus (modern font, code page 437)
.El
.Pp
Valid options for Amiga fonts are:
.Bl -tag -width Er
.It Ic amiga
Alias to Topaz, see below
.It Ic microknight
Original MicroKnight version
.It Ic microknight+
Modified MicroKnight version
.It Ic mosoul
Original mO'sOul font
.It Ic pot-noodle
Original P0T-NOoDLE font
.It Ic topaz
Original Topaz Kickstart 2.x version
.It Ic topaz+
Modified Topaz Kickstart 2.x+ version
.It Ic topaz500
Original Topaz Kickstart 1.x version
.It Ic topaz500+
Modified Topaz Kickstart 1.x version
.El
.It Fl h
Show help
.It Fl i
Enable iCE colors
.It Fl m Ar mode
Set rendering mode for ANS files. Valid options are:
.Bl -tag -width Ds
.It Ic ced
Black on gray, with 78 columns
.It Ic transparent
Render with transparent background
.It Ic workbench
Use Amiga Workbench palette
.El
.It Fl o Ar file
Specify output filename/path
.It Fl r
Creates additional Retina @2x output file
.It Fl R Ar factor
Creates additional Retina output file with custom scale factor
.It Fl s
Show SAUCE record without generating output
.It Fl v
Show version information
.El
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Stefan Vogt ,
.An Brian Cassidy ,
and
.An Frederic Cambus .
